### ISSUE TITLE
META: Turning `hippofactory` into `hippo`, the CLI for Hippo

### ISSUE THREAD

**Issue by technosophos** [deislabs/hippo-cli#31]
We've been talking about using Hippofactory as the basis for the general Hippo CLI. I think these are the major things we would need for a full-fledged UI (some of which are done, and some of which tie closely to demos):

In all of these cases, the assumption is that APP_NAME and other details can be gotten from `./HIPPOFACTS` and that some information can be gained from contacting the API server (e.g. which channels exist, which is default, etc)

## Required

- [ ] `hippo login URL` - login to a Hippo server, after which all ops go to that server
- [ ] `hippo create|remove [APP_NAME]` - create and remove apps. If app name is not specified, use name in `./HIPPOFACTS`
- [ ] `hippo push [CHANNEL]` - push to Bindle and notify the current app on the given (or default) channel.
- [ ] `hippo logs [CHANNEL]` - view logs for the given (or default) channel.
- [ ] `hippo run` - Run the code in a local Wagi instance (for local testing)
- [ ]  `hippo prepare` - Prepare a local bindle, but don't upload
- [ ]  `hippo env set NAME VALUE [CHANNEL]` - Set an env var
- [ ]  `hippo env get|remove NAME VALUE [CHANNEL]` - Set an env var
- [ ] `hippo domain set DNS_NAME [CHANNEL]` - Set the DNS name for an app 
- [ ] `hippo domain get|remove [CHANNEL]` - Get/remove the DNS name for an app. Remove sets it back to the default
- [ ]  `hippo cert set CERT [CHANNEL]` - Set a TLS/SSL cert for a channel (This might need to split cert and key into two files... we can figure that out)
- [ ]  `hippo cert remove [CHANNEL]` - Remove TLS/SSL cert for a channel

## Optional (Possibly unnecessary)
- [ ] `hippo init` - Create a new `HIPPOFACTS` file

## Optional (Maybe UI only)
- [ ] `hippo rollback [CHANNEL]`
- [ ] `hippo pin|unpin CHANNEL RELEASE_VERSION` - pin a channel to a version
- [ ] `hippo channel create|remove CHANNEL`

## Optional (So user doesn't need bindle client, too)
- [ ] `hippo bindle search STRING` - Search the bindle repo, useful for adding dependencies
- [ ] `hippo bindle yank VERSION` - Mark a particular bindle as yanked

## Conventions:

- The convention for commands is `hippo [NOUN] VERB`, with the exception of `hippo logs` (I am open to a verb that means "to read logs" and has some traction in other CLIs)
  - The most common user actions will be on apps, so instead of doing `hippo app create`, `hippo app logs`, etc., I reduced it to `hippo create` and `hippo logs`. This is consistent with the vast majority of CLIs out there.
  - Subgroups are then used for less frequently accessed commands/objects: `hippo channel create`
- I used `remove` instead of `delete` per the [Helm UX research](https://github.com/helm/community/blob/124ab295bd37a4518d96f8e6c989ec73fc1e357e/hips/archives/helm/helm-v3/research/package-manager-ux.md) on the topic, and we could use the `rm` alias if we want

**Comment by bacongobbler** [comment]
I'm in favour of this. Having one tool to interact with bindle would drastically simplify the user experience. It would also drastically simplify the authentication/authorization aspect of Hippo so that we can ensure users can only interact with applications/resources they've been granted access.

I also thought of a few extra commands:

- [ ] `hippo register [username]` - register a new user, opening a prompt for a password.
- [ ] `hippo share [username]` - add an existing user [as a collaborator](https://github.com/deislabs/hippo/blob/1acf4ed897108f7b5ccc677157a57695fc5228ca/Hippo/Models/Application.cs#L32-L33) to an application
- [ ] `hippo unshare [username]` - revoke collaborator access to an application
- [ ] `hippo bindle push .` - accepts and uploads a HIPPOFACTS file (akin to today's `hippofactory -v production .`)

**Comment by bacongobbler** [comment]
Do we need a `hippo unregister` command as well? I'd assume so, but we'd also have to come up with a strategy to ensure applications do not become orphaned by either asking the user change the application's ownership or promote a collaborator as the new "owner" or their apps.

**Comment by technosophos** [comment]
I just updated with `hippo push`, since I think your argument is compelling. I wasn't as keen on `hippo bindle push` for two reasons: (a) it implies a bindle-only op (though IIRC, Hippo is notified on this operation), and (b) `hippo push` is shorter and easier to remember.

**Comment by itowlson** [comment]
> the assumption is that APP_NAME and other details can be gotten from `./HIPPOFACTS`

Unfortunately, this isn't the case at the moment.  The artifacts spec contains a _bindle_ ID, but not an _application_ ID.  Obviously, nothing prevents us changing this, but we'd need to phrase it carefully, because registering a revision affects _all_ applications that use that bindle ID, and we don't want users to think registrations are scoped to that one application.  (Though we can change that too, if we feel the current behaviour is wrong.)

I do like the idea of using the current directory / spec for context, though, so this would definitely be good to investigate.

**Comment by itowlson** [comment]
> The most common user actions will be on apps, so instead of doing `hippo app create` ... I reduced it to `hippo create`

I think this works well for logs but I'm not sure creating new applications will be a day-to-day operation.  I'd vote to keep this one explicit.  (Commenting here because this feels like a de facto spec document, happy to defer or move the discussion if you'd rather.)
